# bulid package
steps:
- name: node:8.12.0-alpine
  id: 'npm-install'
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  id: 'kude-tun-image'
  args: ['build', '-t', '${_GCR_REGISTRY}/kude-tun:${COMMIT_SHA}', '.']
  waitFor: ['npm-install']

# below instead of 'image' section to run in master branch only
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  waitFor: ['kude-tun-image']
  args:
  - '-c'
  - |
    echo "This step only pushes an image if this build was triggered by a push to master."
    [[ "$BRANCH_NAME" == "master" ]] && docker pull ${_GCR_REGISTRY}/kude-tun:${_KUDETUN_IMAGE_VER} || docker tag ${_GCR_REGISTRY}/kude-tun:${COMMIT_SHA} ${_GCR_REGISTRY}/kude-tun:${_KUDETUN_IMAGE_VER} && docker push ${_GCR_REGISTRY}/kude-tun:${_KUDETUN_IMAGE_VER} && docker push ${_GCR_REGISTRY}/kude-tun:${COMMIT_SHA}

substitutions:
  _KUDETUN_IMAGE_VER: 0.1.0
  _GCR_REGISTRY: gcr.io/zarvis-2018
